logo: assets/img/adri.jpg
title: Adrika Chowdhury
description: B. Sc. in Computer Science | Minoring in Mathematics <br> Asian University for Women (AUW) <br> adrika.chowdhury@auw.edu.bd <br> adrikaprachi@gmail.com
theme: jekyll-theme-minimal

