logo: assets/img/adri.jpg
title: Adrika Chowdhury
description: B. Sc. in Computer Science | <br> Minoring in Mathematics | <br> Asian University for Women (AUW)
theme: jekyll-theme-minimal
markdown: Kramdown
