logo: assets/img/adri.jpg
title: Adrika Chowdhury
description: B. Sc. in Computer Science | Minoring in Mathematics
#description: Asian University for Women (AUW)
#description: adrika.chowdhury@auw.edu.bd
#description: adrikaprachi@gmail.com
theme: jekyll-theme-minimal

