title: Adrika Chowdhury
logo: assets/img/adri.jpg
description: B. Sc. in Computer Science
description: Asian University for Women (AUW)
description: adrika.chowdhury@auw.edu.bd
description: adrikaprachi@gmail.com
theme: jekyll-theme-minimal

