logo: assets/img/adri.jpg
title: Adrika Chowdhury
description: B. Sc. in Computer Science | <br> Minoring in Mathematics | <br> Asian University for Women (AUW) <br> <br> adrika.chowdhury@auw.edu.bd <br> adrikaprachi@gmail.com

theme: jekyll-theme-minimal

author:
  name: Adrika Chowdhury
  email: adrika.chowdhury@auw.edu.bd
  
