logo: assets/img/adri.jpg
title: Adrika Chowdhury
description: B. Sc. in Computer Science | Minoring in Mathematics
Asian University for Women (AUW)
adrika.chowdhury@auw.edu.bd
adrikaprachi@gmail.com
theme: jekyll-theme-minimal

