logo: assets/img/adri.jpg
title: Adrika Chowdhury
description: B. Sc. in Computer Science | <br> Minoring in Mathematics <br> Asian University for Women (AUW) <br> <br> adrika.chowdhury@auw.edu.bd <br> adrikaprachi@gmail.com
show_downlaods: true
theme: jekyll-theme-minimal

